name: Run unit tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up node
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Install dependencies
      run: yarn install
    - name: Run tests
      run: yarn test
